/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:7d340b75-8e7a-4b72-bc50-aa261309ac0c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_wAvt783OW",
    "aws_user_pools_web_client_id": "15eeop6tsd5a88jvjs5663l69h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hget33p6mbaozerwg72etdqrwq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-anioj6dzdfcyppaywly5sl3b4q"
};


export default awsmobile;
